# Generated by Django 5.2.14 on 2026-05-07 10:05

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(default='local', max_length=50)),
                ('file_key', models.CharField(db_index=True, max_length=512)),
                ('original_name', models.CharField(max_length=512)),
                ('mime_type', models.CharField(blank=True, max_length=255)),
                ('size', models.BigIntegerField(default=0)),
                ('is_public', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_files', to='organizations.organization')),
            ],
            options={
                'db_table': 'stored_files',
                'ordering': ['-created_at'],
            },
        ),
    ]
