# Generated by Django 5.2.14 on 2026-05-07 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storage_service', '0002_fileforge_architecture'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='storedfile',
            new_name='stored_file_organiz_19fad4_idx',
            old_name='sf_org_prov_idx',
        ),
        migrations.RenameIndex(
            model_name='storedfile',
            new_name='stored_file_status_bb954a_idx',
            old_name='sf_status_idx',
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='file_key',
            field=models.CharField(blank=True, db_index=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='provider',
            field=models.CharField(db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('completed', 'Completed'), ('failed', 'Failed')], db_index=True, default='pending', max_length=16),
        ),
    ]
