# Generated by Django 5.2.14 on 2026-05-07 10:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(db_index=True, max_length=255)),
                ('resource_type', models.CharField(blank=True, db_index=True, max_length=100)),
                ('resource_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('request_id', models.CharField(blank=True, db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(default='success', max_length=20)),
            ],
            options={
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
